"""Initial Migration

Revision ID: dcd86ad9ee69
Revises: f9ee82756586
Create Date: 2021-08-18 22:11:11.567671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd86ad9ee69'
down_revision = 'f9ee82756586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_join', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_join')
    # ### end Alembic commands ###
